name: AbleSci Auto Sign

on:
  workflow_dispatch:

  schedule:
    # UTC 13:40 = 北京时间 21:40
    # UTC 23:40 = 北京时间次日 07:40
    - cron: '40 13,23 * * *'


jobs:

  sign:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.10'
          cache: 'pip'


      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt


      - name: Run AbleSci Sign

        env:

          GITHUB_ACTIONS: "true"

          ABLESCI_COOKIES: ${{ secrets.ABLESCI_COOKIES }}

          # Server酱
          SCKEY: ${{ secrets.SCKEY }}

          # PushPlus
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}

          # 息知
          XZKEY: ${{ secrets.XZKEY }}

        run: |

          python ablesci.py
